# Generated by Django 3.2.5 on 2023-11-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('coeff', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.CharField(max_length=255)),
                ('Etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applabo.etudiant')),
                ('Modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applabo.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='modules', through='applabo.Session', to='applabo.Etudiant'),
        ),
    ]
